- name: Install zsh
  become: true
  package:
    name: zsh
    state: present

# Will figure out later
# - name: Change shell to zsh
#   shell: "chsh -s $(which zsh)"

- name: Check if OhMyZsh exists
  stat:
    path: "{{ home_path }}/.oh-my-zsh"
  register: ohmyzsh_stat

- name: Install OhMyZsh
  when: ohmyzsh_stat.stat.exists == false
  shell: "sh -c $(curl -fsSl https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install zsh auto suggestions
  git:
    repo: "git@github.com:zsh-users/zsh-autosuggestions.git"
    dest: "{{ home_path }}/.oh-my-zsh/plugins/zsh-autosuggestions"

